---

- name: Upload docker-compose.yml
  copy:
    src: files/docker-compose.yml
    dest: /home/bleotard/inception/docker-compose.yml
    owner: bleotard
    group: bleotard
    mode: '0644'
  become: true

- name: Upload .env
  copy:
    src: files/.env
    dest: /home/bleotard/inception/.env
    owner: bleotard
    group: bleotard
    mode: '0644'
  become: true

- name: Upload requirements folder
  copy:
    src: files/requirements
    dest: /home/bleotard/inception/
    owner: bleotard
    group: bleotard
    mode: '0755'
  become: true
