---

- name: Generate a self-signed SSL certificate with VM IP as CN
  shell: |
    openssl req -x509 -nodes -days 365 \
      -newkey rsa:2048 \
      -keyout /etc/nginx/ssl/selfsigned.key \
      -out /etc/nginx/ssl/selfsigned.crt \
      -subj "/CN={{ inventory_hostname }}"
  args:
    creates: /etc/nginx/ssl/selfsigned.crt
  when: inventory_hostname in groups['gcp']

- name: Upload default.conf template with proper server_name
  template:
    src: default.conf.j2
    dest: /home/bleotard/inception/requirements/nginx/conf/default.conf
    owner: bleotard
    group: bleotard
    mode: '0644'