---

- name: Remove existing containers if needed
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - nginx
    - wordpress
    - mariadb
    - phpmyadmin
  ignore_errors: yes
  become: true

- name: Run Docker Compose
  command: docker compose up --build -d
  args:
    chdir: /home/bleotard/inception
  become: true

- name: Check if all expected containers are running
  shell: |
    docker ps --format '{{ "{{.Names}}" }}' | grep -E 'nginx|wordpress|mariadb|phpmyadmin'
  register: running_containers
  failed_when: >
    ('nginx' not in running_containers.stdout) or
    ('wordpress' not in running_containers.stdout) or
    ('mariadb' not in running_containers.stdout) or
    ('phpmyadmin' not in running_containers.stdout)
  changed_when: false
